// Code generated by scripts/gen_audit_model.py. DO NOT EDIT.
// Source: libs/auditmodel/model.yaml + libs/auditmodel/compact_codes.json
//
// Hand edits are reverted on the next generation run. Change the model file.

package auditmodel

// --- Enums ---------------------------------------------------------------

// ActorType: Who initiated an audited action.
type ActorType string

const (
	ActorTypeUser ActorType = "user"
	ActorTypeSystemAdmin ActorType = "system_admin"
	ActorTypeSystem ActorType = "system"
	ActorTypeAnonymous ActorType = "anonymous"
)

// AllActorTypes lists every valid value, for validation and iteration.
var AllActorTypes = []ActorType{
	ActorTypeUser,
	ActorTypeSystemAdmin,
	ActorTypeSystem,
	ActorTypeAnonymous,
}

func (v ActorType) Valid() bool {
	for _, c := range AllActorTypes {
		if v == c {
			return true
		}
	}
	return false
}

// ActorTypeCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var ActorTypeCompact = map[ActorType]string{
	ActorTypeUser: "ACTO2001",
	ActorTypeSystemAdmin: "ACTO2002",
	ActorTypeSystem: "ACTO2003",
	ActorTypeAnonymous: "ACTO2004",
}

// CompactToActorType is the inverse of ActorTypeCompact, for translating a DB read.
var CompactToActorType = map[string]ActorType{
	"ACTO2001": ActorTypeUser,
	"ACTO2002": ActorTypeSystemAdmin,
	"ACTO2003": ActorTypeSystem,
	"ACTO2004": ActorTypeAnonymous,
}

// Outcome: Whether the audited attempt achieved its effect.
type Outcome string

const (
	OutcomeSuccess Outcome = "success"
	OutcomeFailure Outcome = "failure"
	OutcomeDenied Outcome = "denied"
)

// AllOutcomes lists every valid value, for validation and iteration.
var AllOutcomes = []Outcome{
	OutcomeSuccess,
	OutcomeFailure,
	OutcomeDenied,
}

func (v Outcome) Valid() bool {
	for _, c := range AllOutcomes {
		if v == c {
			return true
		}
	}
	return false
}

// OutcomeCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var OutcomeCompact = map[Outcome]string{
	OutcomeSuccess: "OUTC2001",
	OutcomeFailure: "OUTC2002",
	OutcomeDenied: "OUTC2003",
}

// CompactToOutcome is the inverse of OutcomeCompact, for translating a DB read.
var CompactToOutcome = map[string]Outcome{
	"OUTC2001": OutcomeSuccess,
	"OUTC2002": OutcomeFailure,
	"OUTC2003": OutcomeDenied,
}

// Severity: Operational attention an event warrants.
type Severity string

const (
	SeverityInfo Severity = "info"
	SeverityWarn Severity = "warn"
	SeverityError Severity = "error"
	SeverityCritical Severity = "critical"
)

// AllSeveritys lists every valid value, for validation and iteration.
var AllSeveritys = []Severity{
	SeverityInfo,
	SeverityWarn,
	SeverityError,
	SeverityCritical,
}

func (v Severity) Valid() bool {
	for _, c := range AllSeveritys {
		if v == c {
			return true
		}
	}
	return false
}

// SeverityCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var SeverityCompact = map[Severity]string{
	SeverityInfo: "SEVE2001",
	SeverityWarn: "SEVE2002",
	SeverityError: "SEVE2003",
	SeverityCritical: "SEVE2004",
}

// CompactToSeverity is the inverse of SeverityCompact, for translating a DB read.
var CompactToSeverity = map[string]Severity{
	"SEVE2001": SeverityInfo,
	"SEVE2002": SeverityWarn,
	"SEVE2003": SeverityError,
	"SEVE2004": SeverityCritical,
}

// Role: System roles (SRS-AUTH-001 §1.4). Exactly two, deliberately.
type Role string

const (
	RoleUser Role = "user"
	RoleSystemAdmin Role = "system_admin"
)

// AllRoles lists every valid value, for validation and iteration.
var AllRoles = []Role{
	RoleUser,
	RoleSystemAdmin,
}

func (v Role) Valid() bool {
	for _, c := range AllRoles {
		if v == c {
			return true
		}
	}
	return false
}

// RoleCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var RoleCompact = map[Role]string{
	RoleUser: "ROLE2001",
	RoleSystemAdmin: "ROLE2002",
}

// CompactToRole is the inverse of RoleCompact, for translating a DB read.
var CompactToRole = map[string]Role{
	"ROLE2001": RoleUser,
	"ROLE2002": RoleSystemAdmin,
}

// RoutineStatus: Lifecycle of a routine template.
type RoutineStatus string

const (
	RoutineStatusDraft RoutineStatus = "draft"
	RoutineStatusActive RoutineStatus = "active"
	RoutineStatusPaused RoutineStatus = "paused"
	RoutineStatusCompleted RoutineStatus = "completed"
)

// AllRoutineStatuss lists every valid value, for validation and iteration.
var AllRoutineStatuss = []RoutineStatus{
	RoutineStatusDraft,
	RoutineStatusActive,
	RoutineStatusPaused,
	RoutineStatusCompleted,
}

func (v RoutineStatus) Valid() bool {
	for _, c := range AllRoutineStatuss {
		if v == c {
			return true
		}
	}
	return false
}

// RoutineStatusCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var RoutineStatusCompact = map[RoutineStatus]string{
	RoutineStatusDraft: "ROUT2001",
	RoutineStatusActive: "ROUT2002",
	RoutineStatusPaused: "ROUT2003",
	RoutineStatusCompleted: "ROUT2004",
}

// CompactToRoutineStatus is the inverse of RoutineStatusCompact, for translating a DB read.
var CompactToRoutineStatus = map[string]RoutineStatus{
	"ROUT2001": RoutineStatusDraft,
	"ROUT2002": RoutineStatusActive,
	"ROUT2003": RoutineStatusPaused,
	"ROUT2004": RoutineStatusCompleted,
}

// OccurrenceStatus: Lifecycle of one concrete scheduled period.
type OccurrenceStatus string

const (
	OccurrenceStatusUpcoming OccurrenceStatus = "upcoming"
	OccurrenceStatusActive OccurrenceStatus = "active"
	OccurrenceStatusCompleted OccurrenceStatus = "completed"
	OccurrenceStatusSkipped OccurrenceStatus = "skipped"
)

// AllOccurrenceStatuss lists every valid value, for validation and iteration.
var AllOccurrenceStatuss = []OccurrenceStatus{
	OccurrenceStatusUpcoming,
	OccurrenceStatusActive,
	OccurrenceStatusCompleted,
	OccurrenceStatusSkipped,
}

func (v OccurrenceStatus) Valid() bool {
	for _, c := range AllOccurrenceStatuss {
		if v == c {
			return true
		}
	}
	return false
}

// OccurrenceStatusCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var OccurrenceStatusCompact = map[OccurrenceStatus]string{
	OccurrenceStatusUpcoming: "OCCU2001",
	OccurrenceStatusActive: "OCCU2002",
	OccurrenceStatusCompleted: "OCCU2003",
	OccurrenceStatusSkipped: "OCCU2004",
}

// CompactToOccurrenceStatus is the inverse of OccurrenceStatusCompact, for translating a DB read.
var CompactToOccurrenceStatus = map[string]OccurrenceStatus{
	"OCCU2001": OccurrenceStatusUpcoming,
	"OCCU2002": OccurrenceStatusActive,
	"OCCU2003": OccurrenceStatusCompleted,
	"OCCU2004": OccurrenceStatusSkipped,
}

// TaskStatus: State of one task inside an occurrence.
type TaskStatus string

const (
	TaskStatusUnchecked TaskStatus = "unchecked"
	TaskStatusChecked TaskStatus = "checked"
	TaskStatusSkipped TaskStatus = "skipped"
)

// AllTaskStatuss lists every valid value, for validation and iteration.
var AllTaskStatuss = []TaskStatus{
	TaskStatusUnchecked,
	TaskStatusChecked,
	TaskStatusSkipped,
}

func (v TaskStatus) Valid() bool {
	for _, c := range AllTaskStatuss {
		if v == c {
			return true
		}
	}
	return false
}

// TaskStatusCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var TaskStatusCompact = map[TaskStatus]string{
	TaskStatusUnchecked: "TASK2001",
	TaskStatusChecked: "TASK2002",
	TaskStatusSkipped: "TASK2003",
}

// CompactToTaskStatus is the inverse of TaskStatusCompact, for translating a DB read.
var CompactToTaskStatus = map[string]TaskStatus{
	"TASK2001": TaskStatusUnchecked,
	"TASK2002": TaskStatusChecked,
	"TASK2003": TaskStatusSkipped,
}

// PeriodKind: What kind of session a routine period represents.
type PeriodKind string

const (
	PeriodKindResistance PeriodKind = "resistance"
	PeriodKindCardio PeriodKind = "cardio"
	PeriodKindHabit PeriodKind = "habit"
	PeriodKindRest PeriodKind = "rest"
)

// AllPeriodKinds lists every valid value, for validation and iteration.
var AllPeriodKinds = []PeriodKind{
	PeriodKindResistance,
	PeriodKindCardio,
	PeriodKindHabit,
	PeriodKindRest,
}

func (v PeriodKind) Valid() bool {
	for _, c := range AllPeriodKinds {
		if v == c {
			return true
		}
	}
	return false
}

// PeriodKindCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var PeriodKindCompact = map[PeriodKind]string{
	PeriodKindResistance: "PERI2001",
	PeriodKindCardio: "PERI2002",
	PeriodKindHabit: "PERI2003",
	PeriodKindRest: "PERI2004",
}

// CompactToPeriodKind is the inverse of PeriodKindCompact, for translating a DB read.
var CompactToPeriodKind = map[string]PeriodKind{
	"PERI2001": PeriodKindResistance,
	"PERI2002": PeriodKindCardio,
	"PERI2003": PeriodKindHabit,
	"PERI2004": PeriodKindRest,
}

// TrainingType: Training modality. Drives which analytics pipeline applies.
type TrainingType string

const (
	TrainingTypeResistance TrainingType = "resistance"
	TrainingTypeCardio TrainingType = "cardio"
)

// AllTrainingTypes lists every valid value, for validation and iteration.
var AllTrainingTypes = []TrainingType{
	TrainingTypeResistance,
	TrainingTypeCardio,
}

func (v TrainingType) Valid() bool {
	for _, c := range AllTrainingTypes {
		if v == c {
			return true
		}
	}
	return false
}

// TrainingTypeCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var TrainingTypeCompact = map[TrainingType]string{
	TrainingTypeResistance: "TRAI2001",
	TrainingTypeCardio: "TRAI2002",
}

// CompactToTrainingType is the inverse of TrainingTypeCompact, for translating a DB read.
var CompactToTrainingType = map[string]TrainingType{
	"TRAI2001": TrainingTypeResistance,
	"TRAI2002": TrainingTypeCardio,
}

// CalorieSource: How a calorie log entry was produced.
type CalorieSource string

const (
	CalorieSourceManual CalorieSource = "manual"
	CalorieSourcePhoto CalorieSource = "photo"
	CalorieSourceBarcode CalorieSource = "barcode"
)

// AllCalorieSources lists every valid value, for validation and iteration.
var AllCalorieSources = []CalorieSource{
	CalorieSourceManual,
	CalorieSourcePhoto,
	CalorieSourceBarcode,
}

func (v CalorieSource) Valid() bool {
	for _, c := range AllCalorieSources {
		if v == c {
			return true
		}
	}
	return false
}

// CalorieSourceCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var CalorieSourceCompact = map[CalorieSource]string{
	CalorieSourceManual: "CALO2001",
	CalorieSourcePhoto: "CALO2002",
	CalorieSourceBarcode: "CALO2003",
}

// CompactToCalorieSource is the inverse of CalorieSourceCompact, for translating a DB read.
var CompactToCalorieSource = map[string]CalorieSource{
	"CALO2001": CalorieSourceManual,
	"CALO2002": CalorieSourcePhoto,
	"CALO2003": CalorieSourceBarcode,
}

// LinkedProvider: External account types a user can link.
type LinkedProvider string

const (
	LinkedProviderGoogle LinkedProvider = "google"
	LinkedProviderApple LinkedProvider = "apple"
	LinkedProviderQwen LinkedProvider = "qwen"
)

// AllLinkedProviders lists every valid value, for validation and iteration.
var AllLinkedProviders = []LinkedProvider{
	LinkedProviderGoogle,
	LinkedProviderApple,
	LinkedProviderQwen,
}

func (v LinkedProvider) Valid() bool {
	for _, c := range AllLinkedProviders {
		if v == c {
			return true
		}
	}
	return false
}

// LinkedProviderCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var LinkedProviderCompact = map[LinkedProvider]string{
	LinkedProviderGoogle: "LINK2001",
	LinkedProviderApple: "LINK2002",
	LinkedProviderQwen: "LINK2003",
}

// CompactToLinkedProvider is the inverse of LinkedProviderCompact, for translating a DB read.
var CompactToLinkedProvider = map[string]LinkedProvider{
	"LINK2001": LinkedProviderGoogle,
	"LINK2002": LinkedProviderApple,
	"LINK2003": LinkedProviderQwen,
}

// AccountStatus: Whether an account may authenticate (FR-42). Run 1 reads it; run 2 writes it.
type AccountStatus string

const (
	AccountStatusActive AccountStatus = "active"
	AccountStatusSuspended AccountStatus = "suspended"
)

// AllAccountStatuss lists every valid value, for validation and iteration.
var AllAccountStatuss = []AccountStatus{
	AccountStatusActive,
	AccountStatusSuspended,
}

func (v AccountStatus) Valid() bool {
	for _, c := range AllAccountStatuss {
		if v == c {
			return true
		}
	}
	return false
}

// AccountStatusCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var AccountStatusCompact = map[AccountStatus]string{
	AccountStatusActive: "ACCO2001",
	AccountStatusSuspended: "ACCO2002",
}

// CompactToAccountStatus is the inverse of AccountStatusCompact, for translating a DB read.
var CompactToAccountStatus = map[string]AccountStatus{
	"ACCO2001": AccountStatusActive,
	"ACCO2002": AccountStatusSuspended,
}

// LinkKind: What a single-use emailed link authorizes. One table, one lifecycle (SEC-04).
type LinkKind string

const (
	LinkKindEmailVerification LinkKind = "email_verification"
	LinkKindPasswordReset LinkKind = "password_reset"
	LinkKindOauthLink LinkKind = "oauth_link"
)

// AllLinkKinds lists every valid value, for validation and iteration.
var AllLinkKinds = []LinkKind{
	LinkKindEmailVerification,
	LinkKindPasswordReset,
	LinkKindOauthLink,
}

func (v LinkKind) Valid() bool {
	for _, c := range AllLinkKinds {
		if v == c {
			return true
		}
	}
	return false
}

// LinkKindCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var LinkKindCompact = map[LinkKind]string{
	LinkKindEmailVerification: "LINK2004",
	LinkKindPasswordReset: "LINK2005",
	LinkKindOauthLink: "LINK2006",
}

// CompactToLinkKind is the inverse of LinkKindCompact, for translating a DB read.
var CompactToLinkKind = map[string]LinkKind{
	"LINK2004": LinkKindEmailVerification,
	"LINK2005": LinkKindPasswordReset,
	"LINK2006": LinkKindOauthLink,
}

// LinkRejectReason: Why a link token was refused. INTERNAL — all three map to one error code, because telling a caller which one applies tells them whether the token was ever real.
type LinkRejectReason string

const (
	LinkRejectReasonUnknown LinkRejectReason = "unknown"
	LinkRejectReasonExpired LinkRejectReason = "expired"
	LinkRejectReasonAlreadyConsumed LinkRejectReason = "already_consumed"
)

// AllLinkRejectReasons lists every valid value, for validation and iteration.
var AllLinkRejectReasons = []LinkRejectReason{
	LinkRejectReasonUnknown,
	LinkRejectReasonExpired,
	LinkRejectReasonAlreadyConsumed,
}

func (v LinkRejectReason) Valid() bool {
	for _, c := range AllLinkRejectReasons {
		if v == c {
			return true
		}
	}
	return false
}

// LinkRejectReasonCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var LinkRejectReasonCompact = map[LinkRejectReason]string{
	LinkRejectReasonUnknown: "LINK2007",
	LinkRejectReasonExpired: "LINK2008",
	LinkRejectReasonAlreadyConsumed: "LINK2009",
}

// CompactToLinkRejectReason is the inverse of LinkRejectReasonCompact, for translating a DB read.
var CompactToLinkRejectReason = map[string]LinkRejectReason{
	"LINK2007": LinkRejectReasonUnknown,
	"LINK2008": LinkRejectReasonExpired,
	"LINK2009": LinkRejectReasonAlreadyConsumed,
}

// LoginFailureReason: Why a login attempt failed. INTERNAL — this granularity exists for forensics and must never reach the client. See auth.login.failed.
type LoginFailureReason string

const (
	LoginFailureReasonUnknownEmail LoginFailureReason = "unknown_email"
	LoginFailureReasonBadPassword LoginFailureReason = "bad_password"
	LoginFailureReasonAccountSuspended LoginFailureReason = "account_suspended"
	LoginFailureReasonBackoffActive LoginFailureReason = "backoff_active"
	LoginFailureReasonRateLimited LoginFailureReason = "rate_limited"
)

// AllLoginFailureReasons lists every valid value, for validation and iteration.
var AllLoginFailureReasons = []LoginFailureReason{
	LoginFailureReasonUnknownEmail,
	LoginFailureReasonBadPassword,
	LoginFailureReasonAccountSuspended,
	LoginFailureReasonBackoffActive,
	LoginFailureReasonRateLimited,
}

func (v LoginFailureReason) Valid() bool {
	for _, c := range AllLoginFailureReasons {
		if v == c {
			return true
		}
	}
	return false
}

// LoginFailureReasonCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var LoginFailureReasonCompact = map[LoginFailureReason]string{
	LoginFailureReasonUnknownEmail: "LOGI2001",
	LoginFailureReasonBadPassword: "LOGI2002",
	LoginFailureReasonAccountSuspended: "LOGI2003",
	LoginFailureReasonBackoffActive: "LOGI2004",
	LoginFailureReasonRateLimited: "LOGI2005",
}

// CompactToLoginFailureReason is the inverse of LoginFailureReasonCompact, for translating a DB read.
var CompactToLoginFailureReason = map[string]LoginFailureReason{
	"LOGI2001": LoginFailureReasonUnknownEmail,
	"LOGI2002": LoginFailureReasonBadPassword,
	"LOGI2003": LoginFailureReasonAccountSuspended,
	"LOGI2004": LoginFailureReasonBackoffActive,
	"LOGI2005": LoginFailureReasonRateLimited,
}

// TokenRejectReason: Which link in the gateway check chain failed (FR-20). The declared order IS the evaluation order — the first failing check is what gets recorded.
type TokenRejectReason string

const (
	TokenRejectReasonBadSignature TokenRejectReason = "bad_signature"
	TokenRejectReasonExpired TokenRejectReason = "expired"
	TokenRejectReasonBlacklisted TokenRejectReason = "blacklisted"
	TokenRejectReasonEpochStale TokenRejectReason = "epoch_stale"
)

// AllTokenRejectReasons lists every valid value, for validation and iteration.
var AllTokenRejectReasons = []TokenRejectReason{
	TokenRejectReasonBadSignature,
	TokenRejectReasonExpired,
	TokenRejectReasonBlacklisted,
	TokenRejectReasonEpochStale,
}

func (v TokenRejectReason) Valid() bool {
	for _, c := range AllTokenRejectReasons {
		if v == c {
			return true
		}
	}
	return false
}

// TokenRejectReasonCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var TokenRejectReasonCompact = map[TokenRejectReason]string{
	TokenRejectReasonBadSignature: "TOKE2001",
	TokenRejectReasonExpired: "TOKE2002",
	TokenRejectReasonBlacklisted: "TOKE2003",
	TokenRejectReasonEpochStale: "TOKE2004",
}

// CompactToTokenRejectReason is the inverse of TokenRejectReasonCompact, for translating a DB read.
var CompactToTokenRejectReason = map[string]TokenRejectReason{
	"TOKE2001": TokenRejectReasonBadSignature,
	"TOKE2002": TokenRejectReasonExpired,
	"TOKE2003": TokenRejectReasonBlacklisted,
	"TOKE2004": TokenRejectReasonEpochStale,
}

// AdminAction: Administrative actions, each append-only audited (FR-45).
type AdminAction string

const (
	AdminActionSuspend AdminAction = "suspend"
	AdminActionUnsuspend AdminAction = "unsuspend"
	AdminActionForceLogout AdminAction = "force_logout"
	AdminActionRoleGrant AdminAction = "role_grant"
	AdminActionRoleRevoke AdminAction = "role_revoke"
	AdminActionViewSessions AdminAction = "view_sessions"
	AdminActionViewSecurityEvents AdminAction = "view_security_events"
)

// AllAdminActions lists every valid value, for validation and iteration.
var AllAdminActions = []AdminAction{
	AdminActionSuspend,
	AdminActionUnsuspend,
	AdminActionForceLogout,
	AdminActionRoleGrant,
	AdminActionRoleRevoke,
	AdminActionViewSessions,
	AdminActionViewSecurityEvents,
}

func (v AdminAction) Valid() bool {
	for _, c := range AllAdminActions {
		if v == c {
			return true
		}
	}
	return false
}

// AdminActionCompact is the permanent 8-char DB code for each value (docs/audit-and-errors.md §6). Never appears outside the storage layer.
var AdminActionCompact = map[AdminAction]string{
	AdminActionSuspend: "ADMI2001",
	AdminActionUnsuspend: "ADMI2002",
	AdminActionForceLogout: "ADMI2003",
	AdminActionRoleGrant: "ADMI2004",
	AdminActionRoleRevoke: "ADMI2005",
	AdminActionViewSessions: "ADMI2006",
	AdminActionViewSecurityEvents: "ADMI2007",
}

// CompactToAdminAction is the inverse of AdminActionCompact, for translating a DB read.
var CompactToAdminAction = map[string]AdminAction{
	"ADMI2001": AdminActionSuspend,
	"ADMI2002": AdminActionUnsuspend,
	"ADMI2003": AdminActionForceLogout,
	"ADMI2004": AdminActionRoleGrant,
	"ADMI2005": AdminActionRoleRevoke,
	"ADMI2006": AdminActionViewSessions,
	"ADMI2007": AdminActionViewSecurityEvents,
}

// --- Error codes ---------------------------------------------------------

type ErrorCode string

const (
	ErrAuthInvalidCredentials ErrorCode = "AUTH_INVALID_CREDENTIALS"
	ErrAuthInvalidToken ErrorCode = "AUTH_INVALID_TOKEN"
	ErrAuthSessionExpired ErrorCode = "AUTH_SESSION_EXPIRED"
	ErrAuthForbidden ErrorCode = "AUTH_FORBIDDEN"
	ErrAuthCsrfFailed ErrorCode = "AUTH_CSRF_FAILED"
	ErrAuthAccountSuspended ErrorCode = "AUTH_ACCOUNT_SUSPENDED"
	ErrAuthEmailUnverified ErrorCode = "AUTH_EMAIL_UNVERIFIED"
	ErrAuthLinkInvalid ErrorCode = "AUTH_LINK_INVALID"
	ErrAuthRateLimited ErrorCode = "AUTH_RATE_LIMITED"
	ErrValidationFailed ErrorCode = "VALIDATION_FAILED"
	ErrServiceUnavailable ErrorCode = "SERVICE_UNAVAILABLE"
	ErrInternalError ErrorCode = "INTERNAL_ERROR"
)

// ErrorCodeSpec carries what the API layer needs to build an error envelope.
//
// There is no message text here. The envelope's message is rendered by the
// server from libs/i18n/locales/<locale>.json, keyed by the code itself,
// using the request's Accept-Language. See libs/i18n/README.md.
type ErrorCodeSpec struct {
	HTTPStatus int
}

var ErrorCodes = map[ErrorCode]ErrorCodeSpec{
	ErrAuthInvalidCredentials: {HTTPStatus: 401},
	ErrAuthInvalidToken: {HTTPStatus: 401},
	ErrAuthSessionExpired: {HTTPStatus: 401},
	ErrAuthForbidden: {HTTPStatus: 403},
	ErrAuthCsrfFailed: {HTTPStatus: 403},
	ErrAuthAccountSuspended: {HTTPStatus: 403},
	ErrAuthEmailUnverified: {HTTPStatus: 403},
	ErrAuthLinkInvalid: {HTTPStatus: 400},
	ErrAuthRateLimited: {HTTPStatus: 429},
	ErrValidationFailed: {HTTPStatus: 400},
	ErrServiceUnavailable: {HTTPStatus: 503},
	ErrInternalError: {HTTPStatus: 500},
}

// AllErrorCodes lets a catalog completeness test iterate every code.
var AllErrorCodes = []ErrorCode{
	ErrAuthInvalidCredentials,
	ErrAuthInvalidToken,
	ErrAuthSessionExpired,
	ErrAuthForbidden,
	ErrAuthCsrfFailed,
	ErrAuthAccountSuspended,
	ErrAuthEmailUnverified,
	ErrAuthLinkInvalid,
	ErrAuthRateLimited,
	ErrValidationFailed,
	ErrServiceUnavailable,
	ErrInternalError,
}

// ErrorCodeCompact is the permanent 8-char DB code for each error code (docs/audit-and-errors.md §6). Never appears in an API response.
var ErrorCodeCompact = map[ErrorCode]string{
	ErrAuthInvalidCredentials: "AUTH0001",
	ErrAuthInvalidToken: "AUTH0002",
	ErrAuthSessionExpired: "AUTH0003",
	ErrAuthForbidden: "AUTH0004",
	ErrAuthCsrfFailed: "AUTH0005",
	ErrAuthAccountSuspended: "AUTH0006",
	ErrAuthEmailUnverified: "AUTH0008",
	ErrAuthLinkInvalid: "AUTH0009",
	ErrAuthRateLimited: "AUTH0007",
	ErrValidationFailed: "VALI0001",
	ErrServiceUnavailable: "SERV0001",
	ErrInternalError: "INTE0001",
}

// CompactToErrorCode is the inverse of ErrorCodeCompact, for translating a DB read.
var CompactToErrorCode = map[string]ErrorCode{
	"AUTH0001": ErrAuthInvalidCredentials,
	"AUTH0002": ErrAuthInvalidToken,
	"AUTH0003": ErrAuthSessionExpired,
	"AUTH0004": ErrAuthForbidden,
	"AUTH0005": ErrAuthCsrfFailed,
	"AUTH0006": ErrAuthAccountSuspended,
	"AUTH0008": ErrAuthEmailUnverified,
	"AUTH0009": ErrAuthLinkInvalid,
	"AUTH0007": ErrAuthRateLimited,
	"VALI0001": ErrValidationFailed,
	"SERV0001": ErrServiceUnavailable,
	"INTE0001": ErrInternalError,
}

// --- Audit events --------------------------------------------------------

type AuditEvent string

const (
	// A new account was created.
	EvtAuthRegisterSucceeded AuditEvent = "auth.register.succeeded"
	// Credentials or OAuth accepted; a session was established.
	EvtAuthLoginSucceeded AuditEvent = "auth.login.succeeded"
	// A login attempt failed. The `reason` enum is the whole point of this event — it is what makes "how many failures were rate-limits this week" answerable. It is ALSO why this event must never be rendered to a client.
	EvtAuthLoginFailed AuditEvent = "auth.login.failed"
	// Fifth consecutive failure for an account; backoff begins (FR-13).
	EvtAuthLoginBackoffTriggered AuditEvent = "auth.login.backoff_triggered"
	// Gateway rejected an access token. `reason` is the FIRST failing check.
	EvtAuthTokenRejected AuditEvent = "auth.token.rejected"
	// Refresh token exchanged for a new pair; old jti blacklisted (FR-30).
	EvtAuthRefreshRotated AuditEvent = "auth.refresh.rotated"
	// An already-rotated refresh token was presented (FR-31). Treated as a stolen token: every session for the user is revoked. Flagged WARN+ by NFR-07 — this is the event most worth alerting on in the whole system.
	EvtAuthRefreshReplayDetected AuditEvent = "auth.refresh.replay_detected"
	// Single-session logout; tokens blacklisted (FR-32).
	EvtAuthLogout AuditEvent = "auth.logout"
	// Epoch advanced, revoking every session (FR-33). Also emitted when triggered indirectly by password reset or admin action — `trigger` says which, so a spike in admin-triggered logouts is distinguishable from a spike in user-initiated ones.
	EvtAuthLogoutAll AuditEvent = "auth.logout_all"
	// One specific session revoked from the session list (FR-41).
	EvtAuthSessionRevoked AuditEvent = "auth.session.revoked"
	// Password changed via reset token; triggers logout-all (FR-07).
	EvtAuthPasswordResetCompleted AuditEvent = "auth.password_reset.completed"
	// Any SystemAdmin action (FR-45). Append-only; no API may delete these. One event with an `action` enum rather than seven near-identical events — every admin action needs the same five fields, and a single event keeps "show me everything this admin did" a single query.
	EvtAdminActionPerformed AuditEvent = "admin.action.performed"
	// A non-admin token attempted an admin endpoint (FR-22, logged per §6 AC-5).
	EvtAdminActionDenied AuditEvent = "admin.action.denied"
	// A login attempt succeeded against a suspended account. Separated from auth.login.failed so this outcome can carry AUTH_ACCOUNT_SUSPENDED while wrong-password/unknown-email still carries AUTH_INVALID_CREDENTIALS (D2).
	EvtAuthLoginSuspended AuditEvent = "auth.login.suspended"
	// An account confirmed control of its email address via a verification link (FR-03).
	EvtAuthEmailVerified AuditEvent = "auth.email.verified"
	// A single-use emailed link token was refused. One event for all three LinkRejectReason values, mapping to one error code — the distinction between "never existed" and "already used" must not reach the caller (SEC-04).
	EvtAuthLinkRejected AuditEvent = "auth.link.rejected"
	// A password-reset email was requested (FR-07). Emitted whether or not the address is known — the response is byte-identical either way to prevent account enumeration; user_id is absent when the address is unknown.
	EvtAuthPasswordResetRequested AuditEvent = "auth.password_reset.requested"
	// An OAuth callback found the email already owned by a local account with no linked identity; a link token was emailed and the browser redirected (FR-06, §4.3).
	EvtAuthOauthLinkRequired AuditEvent = "auth.oauth.link_required"
	// An authenticated but unverified account attempted an unsafe-method request; gateway middleware blocked it (FR-03, D4).
	EvtAuthWriteBlockedUnverified AuditEvent = "auth.write_blocked_unverified"
)

// AuditEventSpec describes one event's fixed attributes and its declared fields.
// RequiredFields is what an emitter must supply; emitting without them is a bug
// that leaves an unqueryable record in an append-only store. OptionalFields lists
// every field declared `optional: true` in model.yaml. Together, RequiredFields
// plus OptionalFields is the complete declared set for the event — a writer needs
// both to reject a field the event never declared, not just to check presence of
// the required ones (added by AMD-001-auth-epic amendment AMD-002, libs-auditlog).
type AuditEventSpec struct {
	Actor          ActorType
	Outcome        Outcome
	Severity       Severity
	Message        string
	RequiredFields []string
	OptionalFields []string
	ErrorCode      ErrorCode // empty when the event surfaces nothing to the caller
}

var AuditEvents = map[AuditEvent]AuditEventSpec{
	EvtAuthRegisterSucceeded: {
		Actor:          ActorTypeAnonymous,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityInfo,
		Message:        "Account created for {user_id}",
		RequiredFields: []string{"user_id"},
		OptionalFields: []string{"via"},
		ErrorCode:      "",
	},
	EvtAuthLoginSucceeded: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityInfo,
		Message:        "Login succeeded for {user_id} from {device_label}",
		RequiredFields: []string{"user_id", "session_jti", "source_ip"},
		OptionalFields: []string{"device_label"},
		ErrorCode:      "",
	},
	EvtAuthLoginFailed: {
		Actor:          ActorTypeAnonymous,
		Outcome:        OutcomeFailure,
		Severity:       SeverityWarn,
		Message:        "Login failed ({reason}) from {source_ip}",
		RequiredFields: []string{"reason", "source_ip"},
		OptionalFields: []string{"user_id"},
		ErrorCode:      ErrAuthInvalidCredentials,
	},
	EvtAuthLoginBackoffTriggered: {
		Actor:          ActorTypeAnonymous,
		Outcome:        OutcomeDenied,
		Severity:       SeverityWarn,
		Message:        "Backoff started for {user_id}: {delay_seconds}s",
		RequiredFields: []string{"user_id", "delay_seconds", "source_ip"},
		OptionalFields: []string{},
		ErrorCode:      ErrAuthRateLimited,
	},
	EvtAuthTokenRejected: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeDenied,
		Severity:       SeverityInfo,
		Message:        "Token rejected ({reason}) jti={jti}",
		RequiredFields: []string{"reason", "jti", "request_id"},
		OptionalFields: []string{"user_id"},
		ErrorCode:      ErrAuthInvalidToken,
	},
	EvtAuthRefreshRotated: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityInfo,
		Message:        "Refresh rotated for {user_id}",
		RequiredFields: []string{"user_id", "old_jti", "new_jti"},
		OptionalFields: []string{},
		ErrorCode:      "",
	},
	EvtAuthRefreshReplayDetected: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeDenied,
		Severity:       SeverityCritical,
		Message:        "Refresh replay detected for {user_id}; all sessions revoked",
		RequiredFields: []string{"user_id", "replayed_jti", "source_ip"},
		OptionalFields: []string{},
		ErrorCode:      ErrAuthInvalidToken,
	},
	EvtAuthLogout: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityInfo,
		Message:        "Logout for {user_id}",
		RequiredFields: []string{"user_id", "session_jti"},
		OptionalFields: []string{},
		ErrorCode:      "",
	},
	EvtAuthLogoutAll: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityInfo,
		Message:        "All sessions revoked for {user_id}",
		RequiredFields: []string{"user_id"},
		OptionalFields: []string{"trigger"},
		ErrorCode:      "",
	},
	EvtAuthSessionRevoked: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityInfo,
		Message:        "Session {revoked_jti} revoked by {user_id}",
		RequiredFields: []string{"user_id", "revoked_jti"},
		OptionalFields: []string{},
		ErrorCode:      "",
	},
	EvtAuthPasswordResetCompleted: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityWarn,
		Message:        "Password reset completed for {user_id}",
		RequiredFields: []string{"user_id", "source_ip"},
		OptionalFields: []string{},
		ErrorCode:      "",
	},
	EvtAdminActionPerformed: {
		Actor:          ActorTypeSystemAdmin,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityWarn,
		Message:        "Admin {admin_id} performed {action} on {target_user_id}",
		RequiredFields: []string{"action", "admin_id", "target_user_id", "request_id"},
		OptionalFields: []string{"new_role"},
		ErrorCode:      "",
	},
	EvtAdminActionDenied: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeDenied,
		Severity:       SeverityWarn,
		Message:        "Forbidden admin access attempt by {user_id} on {path}",
		RequiredFields: []string{"user_id", "path", "request_id"},
		OptionalFields: []string{},
		ErrorCode:      ErrAuthForbidden,
	},
	EvtAuthLoginSuspended: {
		Actor:          ActorTypeAnonymous,
		Outcome:        OutcomeDenied,
		Severity:       SeverityWarn,
		Message:        "Login denied for suspended account {user_id} from {source_ip}",
		RequiredFields: []string{"user_id", "source_ip"},
		OptionalFields: []string{},
		ErrorCode:      ErrAuthAccountSuspended,
	},
	EvtAuthEmailVerified: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityInfo,
		Message:        "Email verified for {user_id}",
		RequiredFields: []string{"user_id"},
		OptionalFields: []string{},
		ErrorCode:      "",
	},
	EvtAuthLinkRejected: {
		Actor:          ActorTypeAnonymous,
		Outcome:        OutcomeFailure,
		Severity:       SeverityWarn,
		Message:        "Link rejected ({kind}:{reason}) from {source_ip}",
		RequiredFields: []string{"kind", "reason", "source_ip"},
		OptionalFields: []string{"user_id"},
		ErrorCode:      ErrAuthLinkInvalid,
	},
	EvtAuthPasswordResetRequested: {
		Actor:          ActorTypeAnonymous,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityInfo,
		Message:        "Password reset requested from {source_ip}",
		RequiredFields: []string{"source_ip"},
		OptionalFields: []string{"user_id"},
		ErrorCode:      "",
	},
	EvtAuthOauthLinkRequired: {
		Actor:          ActorTypeAnonymous,
		Outcome:        OutcomeDenied,
		Severity:       SeverityWarn,
		Message:        "OAuth link required for {user_id} ({provider}) from {source_ip}",
		RequiredFields: []string{"user_id", "provider", "source_ip"},
		OptionalFields: []string{},
		ErrorCode:      "",
	},
	EvtAuthWriteBlockedUnverified: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeDenied,
		Severity:       SeverityInfo,
		Message:        "Write blocked (unverified email) for {user_id} on {path}",
		RequiredFields: []string{"user_id", "path", "request_id"},
		OptionalFields: []string{},
		ErrorCode:      ErrAuthEmailUnverified,
	},
}

// AuditEventCompact is the permanent 8-char DB code for each audit event (docs/audit-and-errors.md §6). Never appears in a rendered audit message.
var AuditEventCompact = map[AuditEvent]string{
	EvtAuthRegisterSucceeded: "AUTH1001",
	EvtAuthLoginSucceeded: "AUTH1002",
	EvtAuthLoginFailed: "AUTH1003",
	EvtAuthLoginBackoffTriggered: "AUTH1004",
	EvtAuthTokenRejected: "AUTH1005",
	EvtAuthRefreshRotated: "AUTH1006",
	EvtAuthRefreshReplayDetected: "AUTH1007",
	EvtAuthLogout: "AUTH1008",
	EvtAuthLogoutAll: "AUTH1009",
	EvtAuthSessionRevoked: "AUTH1010",
	EvtAuthPasswordResetCompleted: "AUTH1011",
	EvtAdminActionPerformed: "ADMI1001",
	EvtAdminActionDenied: "ADMI1002",
	EvtAuthLoginSuspended: "AUTH1012",
	EvtAuthEmailVerified: "AUTH1013",
	EvtAuthLinkRejected: "AUTH1014",
	EvtAuthPasswordResetRequested: "AUTH1015",
	EvtAuthOauthLinkRequired: "AUTH1016",
	EvtAuthWriteBlockedUnverified: "AUTH1017",
}

// CompactToAuditEvent is the inverse of AuditEventCompact, for translating a DB read.
var CompactToAuditEvent = map[string]AuditEvent{
	"AUTH1001": EvtAuthRegisterSucceeded,
	"AUTH1002": EvtAuthLoginSucceeded,
	"AUTH1003": EvtAuthLoginFailed,
	"AUTH1004": EvtAuthLoginBackoffTriggered,
	"AUTH1005": EvtAuthTokenRejected,
	"AUTH1006": EvtAuthRefreshRotated,
	"AUTH1007": EvtAuthRefreshReplayDetected,
	"AUTH1008": EvtAuthLogout,
	"AUTH1009": EvtAuthLogoutAll,
	"AUTH1010": EvtAuthSessionRevoked,
	"AUTH1011": EvtAuthPasswordResetCompleted,
	"ADMI1001": EvtAdminActionPerformed,
	"ADMI1002": EvtAdminActionDenied,
	"AUTH1012": EvtAuthLoginSuspended,
	"AUTH1013": EvtAuthEmailVerified,
	"AUTH1014": EvtAuthLinkRejected,
	"AUTH1015": EvtAuthPasswordResetRequested,
	"AUTH1016": EvtAuthOauthLinkRequired,
	"AUTH1017": EvtAuthWriteBlockedUnverified,
}
