// Code generated by scripts/gen_audit_model.py. DO NOT EDIT.
// Source: libs/auditmodel/model.yaml
//
// Hand edits are reverted on the next generation run. Change the model file.

package auditmodel

// --- Enums ---------------------------------------------------------------

// ActorType: Who initiated an audited action.
type ActorType string

const (
	ActorTypeUser ActorType = "user"
	ActorTypeSystemAdmin ActorType = "system_admin"
	ActorTypeSystem ActorType = "system"
	ActorTypeAnonymous ActorType = "anonymous"
)

// AllActorTypes lists every valid value, for validation and iteration.
var AllActorTypes = []ActorType{
	ActorTypeUser,
	ActorTypeSystemAdmin,
	ActorTypeSystem,
	ActorTypeAnonymous,
}

func (v ActorType) Valid() bool {
	for _, c := range AllActorTypes {
		if v == c {
			return true
		}
	}
	return false
}

// Outcome: Whether the audited attempt achieved its effect.
type Outcome string

const (
	OutcomeSuccess Outcome = "success"
	OutcomeFailure Outcome = "failure"
	OutcomeDenied Outcome = "denied"
)

// AllOutcomes lists every valid value, for validation and iteration.
var AllOutcomes = []Outcome{
	OutcomeSuccess,
	OutcomeFailure,
	OutcomeDenied,
}

func (v Outcome) Valid() bool {
	for _, c := range AllOutcomes {
		if v == c {
			return true
		}
	}
	return false
}

// Severity: Operational attention an event warrants.
type Severity string

const (
	SeverityInfo Severity = "info"
	SeverityWarn Severity = "warn"
	SeverityError Severity = "error"
	SeverityCritical Severity = "critical"
)

// AllSeveritys lists every valid value, for validation and iteration.
var AllSeveritys = []Severity{
	SeverityInfo,
	SeverityWarn,
	SeverityError,
	SeverityCritical,
}

func (v Severity) Valid() bool {
	for _, c := range AllSeveritys {
		if v == c {
			return true
		}
	}
	return false
}

// Role: System roles (SRS-AUTH-001 §1.4). Exactly two, deliberately.
type Role string

const (
	RoleUser Role = "user"
	RoleSystemAdmin Role = "system_admin"
)

// AllRoles lists every valid value, for validation and iteration.
var AllRoles = []Role{
	RoleUser,
	RoleSystemAdmin,
}

func (v Role) Valid() bool {
	for _, c := range AllRoles {
		if v == c {
			return true
		}
	}
	return false
}

// RoutineStatus: Lifecycle of a routine template.
type RoutineStatus string

const (
	RoutineStatusDraft RoutineStatus = "draft"
	RoutineStatusActive RoutineStatus = "active"
	RoutineStatusPaused RoutineStatus = "paused"
	RoutineStatusCompleted RoutineStatus = "completed"
)

// AllRoutineStatuss lists every valid value, for validation and iteration.
var AllRoutineStatuss = []RoutineStatus{
	RoutineStatusDraft,
	RoutineStatusActive,
	RoutineStatusPaused,
	RoutineStatusCompleted,
}

func (v RoutineStatus) Valid() bool {
	for _, c := range AllRoutineStatuss {
		if v == c {
			return true
		}
	}
	return false
}

// OccurrenceStatus: Lifecycle of one concrete scheduled period.
type OccurrenceStatus string

const (
	OccurrenceStatusUpcoming OccurrenceStatus = "upcoming"
	OccurrenceStatusActive OccurrenceStatus = "active"
	OccurrenceStatusCompleted OccurrenceStatus = "completed"
	OccurrenceStatusSkipped OccurrenceStatus = "skipped"
)

// AllOccurrenceStatuss lists every valid value, for validation and iteration.
var AllOccurrenceStatuss = []OccurrenceStatus{
	OccurrenceStatusUpcoming,
	OccurrenceStatusActive,
	OccurrenceStatusCompleted,
	OccurrenceStatusSkipped,
}

func (v OccurrenceStatus) Valid() bool {
	for _, c := range AllOccurrenceStatuss {
		if v == c {
			return true
		}
	}
	return false
}

// TaskStatus: State of one task inside an occurrence.
type TaskStatus string

const (
	TaskStatusUnchecked TaskStatus = "unchecked"
	TaskStatusChecked TaskStatus = "checked"
	TaskStatusSkipped TaskStatus = "skipped"
)

// AllTaskStatuss lists every valid value, for validation and iteration.
var AllTaskStatuss = []TaskStatus{
	TaskStatusUnchecked,
	TaskStatusChecked,
	TaskStatusSkipped,
}

func (v TaskStatus) Valid() bool {
	for _, c := range AllTaskStatuss {
		if v == c {
			return true
		}
	}
	return false
}

// PeriodKind: What kind of session a routine period represents.
type PeriodKind string

const (
	PeriodKindResistance PeriodKind = "resistance"
	PeriodKindCardio PeriodKind = "cardio"
	PeriodKindHabit PeriodKind = "habit"
	PeriodKindRest PeriodKind = "rest"
)

// AllPeriodKinds lists every valid value, for validation and iteration.
var AllPeriodKinds = []PeriodKind{
	PeriodKindResistance,
	PeriodKindCardio,
	PeriodKindHabit,
	PeriodKindRest,
}

func (v PeriodKind) Valid() bool {
	for _, c := range AllPeriodKinds {
		if v == c {
			return true
		}
	}
	return false
}

// TrainingType: Training modality. Drives which analytics pipeline applies.
type TrainingType string

const (
	TrainingTypeResistance TrainingType = "resistance"
	TrainingTypeCardio TrainingType = "cardio"
)

// AllTrainingTypes lists every valid value, for validation and iteration.
var AllTrainingTypes = []TrainingType{
	TrainingTypeResistance,
	TrainingTypeCardio,
}

func (v TrainingType) Valid() bool {
	for _, c := range AllTrainingTypes {
		if v == c {
			return true
		}
	}
	return false
}

// CalorieSource: How a calorie log entry was produced.
type CalorieSource string

const (
	CalorieSourceManual CalorieSource = "manual"
	CalorieSourcePhoto CalorieSource = "photo"
	CalorieSourceBarcode CalorieSource = "barcode"
)

// AllCalorieSources lists every valid value, for validation and iteration.
var AllCalorieSources = []CalorieSource{
	CalorieSourceManual,
	CalorieSourcePhoto,
	CalorieSourceBarcode,
}

func (v CalorieSource) Valid() bool {
	for _, c := range AllCalorieSources {
		if v == c {
			return true
		}
	}
	return false
}

// LinkedProvider: External account types a user can link.
type LinkedProvider string

const (
	LinkedProviderGoogle LinkedProvider = "google"
	LinkedProviderApple LinkedProvider = "apple"
	LinkedProviderQwen LinkedProvider = "qwen"
)

// AllLinkedProviders lists every valid value, for validation and iteration.
var AllLinkedProviders = []LinkedProvider{
	LinkedProviderGoogle,
	LinkedProviderApple,
	LinkedProviderQwen,
}

func (v LinkedProvider) Valid() bool {
	for _, c := range AllLinkedProviders {
		if v == c {
			return true
		}
	}
	return false
}

// LoginFailureReason: Why a login attempt failed. INTERNAL — this granularity exists for forensics and must never reach the client. See auth.login.failed.
type LoginFailureReason string

const (
	LoginFailureReasonUnknownEmail LoginFailureReason = "unknown_email"
	LoginFailureReasonBadPassword LoginFailureReason = "bad_password"
	LoginFailureReasonAccountSuspended LoginFailureReason = "account_suspended"
	LoginFailureReasonBackoffActive LoginFailureReason = "backoff_active"
	LoginFailureReasonRateLimited LoginFailureReason = "rate_limited"
)

// AllLoginFailureReasons lists every valid value, for validation and iteration.
var AllLoginFailureReasons = []LoginFailureReason{
	LoginFailureReasonUnknownEmail,
	LoginFailureReasonBadPassword,
	LoginFailureReasonAccountSuspended,
	LoginFailureReasonBackoffActive,
	LoginFailureReasonRateLimited,
}

func (v LoginFailureReason) Valid() bool {
	for _, c := range AllLoginFailureReasons {
		if v == c {
			return true
		}
	}
	return false
}

// TokenRejectReason: Which link in the gateway check chain failed (FR-20). The declared order IS the evaluation order — the first failing check is what gets recorded.
type TokenRejectReason string

const (
	TokenRejectReasonBadSignature TokenRejectReason = "bad_signature"
	TokenRejectReasonExpired TokenRejectReason = "expired"
	TokenRejectReasonBlacklisted TokenRejectReason = "blacklisted"
	TokenRejectReasonEpochStale TokenRejectReason = "epoch_stale"
)

// AllTokenRejectReasons lists every valid value, for validation and iteration.
var AllTokenRejectReasons = []TokenRejectReason{
	TokenRejectReasonBadSignature,
	TokenRejectReasonExpired,
	TokenRejectReasonBlacklisted,
	TokenRejectReasonEpochStale,
}

func (v TokenRejectReason) Valid() bool {
	for _, c := range AllTokenRejectReasons {
		if v == c {
			return true
		}
	}
	return false
}

// AdminAction: Administrative actions, each append-only audited (FR-45).
type AdminAction string

const (
	AdminActionSuspend AdminAction = "suspend"
	AdminActionUnsuspend AdminAction = "unsuspend"
	AdminActionForceLogout AdminAction = "force_logout"
	AdminActionRoleGrant AdminAction = "role_grant"
	AdminActionRoleRevoke AdminAction = "role_revoke"
	AdminActionViewSessions AdminAction = "view_sessions"
	AdminActionViewSecurityEvents AdminAction = "view_security_events"
)

// AllAdminActions lists every valid value, for validation and iteration.
var AllAdminActions = []AdminAction{
	AdminActionSuspend,
	AdminActionUnsuspend,
	AdminActionForceLogout,
	AdminActionRoleGrant,
	AdminActionRoleRevoke,
	AdminActionViewSessions,
	AdminActionViewSecurityEvents,
}

func (v AdminAction) Valid() bool {
	for _, c := range AllAdminActions {
		if v == c {
			return true
		}
	}
	return false
}

// --- Error codes ---------------------------------------------------------

type ErrorCode string

const (
	ErrAuthInvalidCredentials ErrorCode = "AUTH_INVALID_CREDENTIALS"
	ErrAuthInvalidToken ErrorCode = "AUTH_INVALID_TOKEN"
	ErrAuthSessionExpired ErrorCode = "AUTH_SESSION_EXPIRED"
	ErrAuthForbidden ErrorCode = "AUTH_FORBIDDEN"
	ErrAuthCsrfFailed ErrorCode = "AUTH_CSRF_FAILED"
	ErrAuthAccountSuspended ErrorCode = "AUTH_ACCOUNT_SUSPENDED"
	ErrAuthRateLimited ErrorCode = "AUTH_RATE_LIMITED"
	ErrValidationFailed ErrorCode = "VALIDATION_FAILED"
)

// ErrorCodeSpec carries what the API layer needs to build an error envelope.
//
// There is no message text here. The envelope's message is rendered by the
// server from libs/i18n/locales/<locale>.json, keyed by the code itself,
// using the request's Accept-Language. See libs/i18n/README.md.
type ErrorCodeSpec struct {
	HTTPStatus int
}

var ErrorCodes = map[ErrorCode]ErrorCodeSpec{
	ErrAuthInvalidCredentials: {HTTPStatus: 401},
	ErrAuthInvalidToken: {HTTPStatus: 401},
	ErrAuthSessionExpired: {HTTPStatus: 401},
	ErrAuthForbidden: {HTTPStatus: 403},
	ErrAuthCsrfFailed: {HTTPStatus: 403},
	ErrAuthAccountSuspended: {HTTPStatus: 403},
	ErrAuthRateLimited: {HTTPStatus: 429},
	ErrValidationFailed: {HTTPStatus: 400},
}

// AllErrorCodes lets a catalog completeness test iterate every code.
var AllErrorCodes = []ErrorCode{
	ErrAuthInvalidCredentials,
	ErrAuthInvalidToken,
	ErrAuthSessionExpired,
	ErrAuthForbidden,
	ErrAuthCsrfFailed,
	ErrAuthAccountSuspended,
	ErrAuthRateLimited,
	ErrValidationFailed,
}

// --- Audit events --------------------------------------------------------

type AuditEvent string

const (
	// A new account was created.
	EvtAuthRegisterSucceeded AuditEvent = "auth.register.succeeded"
	// Credentials or OAuth accepted; a session was established.
	EvtAuthLoginSucceeded AuditEvent = "auth.login.succeeded"
	// A login attempt failed. The `reason` enum is the whole point of this event — it is what makes "how many failures were rate-limits this week" answerable. It is ALSO why this event must never be rendered to a client.
	EvtAuthLoginFailed AuditEvent = "auth.login.failed"
	// Fifth consecutive failure for an account; backoff begins (FR-13).
	EvtAuthLoginBackoffTriggered AuditEvent = "auth.login.backoff_triggered"
	// Gateway rejected an access token. `reason` is the FIRST failing check.
	EvtAuthTokenRejected AuditEvent = "auth.token.rejected"
	// Refresh token exchanged for a new pair; old jti blacklisted (FR-30).
	EvtAuthRefreshRotated AuditEvent = "auth.refresh.rotated"
	// An already-rotated refresh token was presented (FR-31). Treated as a stolen token: every session for the user is revoked. Flagged WARN+ by NFR-07 — this is the event most worth alerting on in the whole system.
	EvtAuthRefreshReplayDetected AuditEvent = "auth.refresh.replay_detected"
	// Single-session logout; tokens blacklisted (FR-32).
	EvtAuthLogout AuditEvent = "auth.logout"
	// Epoch advanced, revoking every session (FR-33). Also emitted when triggered indirectly by password reset or admin action — `trigger` says which, so a spike in admin-triggered logouts is distinguishable from a spike in user-initiated ones.
	EvtAuthLogoutAll AuditEvent = "auth.logout_all"
	// One specific session revoked from the session list (FR-41).
	EvtAuthSessionRevoked AuditEvent = "auth.session.revoked"
	// Password changed via reset token; triggers logout-all (FR-07).
	EvtAuthPasswordResetCompleted AuditEvent = "auth.password_reset.completed"
	// Any SystemAdmin action (FR-45). Append-only; no API may delete these. One event with an `action` enum rather than seven near-identical events — every admin action needs the same five fields, and a single event keeps "show me everything this admin did" a single query.
	EvtAdminActionPerformed AuditEvent = "admin.action.performed"
	// A non-admin token attempted an admin endpoint (FR-22, logged per §6 AC-5).
	EvtAdminActionDenied AuditEvent = "admin.action.denied"
)

// AuditEventSpec describes one event's fixed attributes and its declared fields.
// RequiredFields is what an emitter must supply; emitting without them is a bug
// that leaves an unqueryable record in an append-only store.
type AuditEventSpec struct {
	Actor          ActorType
	Outcome        Outcome
	Severity       Severity
	Message        string
	RequiredFields []string
	ErrorCode      ErrorCode // empty when the event surfaces nothing to the caller
}

var AuditEvents = map[AuditEvent]AuditEventSpec{
	EvtAuthRegisterSucceeded: {
		Actor:          ActorTypeAnonymous,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityInfo,
		Message:        "Account created for {user_id}",
		RequiredFields: []string{"user_id"},
		ErrorCode:      "",
	},
	EvtAuthLoginSucceeded: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityInfo,
		Message:        "Login succeeded for {user_id} from {device_label}",
		RequiredFields: []string{"user_id", "session_jti", "source_ip"},
		ErrorCode:      "",
	},
	EvtAuthLoginFailed: {
		Actor:          ActorTypeAnonymous,
		Outcome:        OutcomeFailure,
		Severity:       SeverityWarn,
		Message:        "Login failed ({reason}) from {source_ip}",
		RequiredFields: []string{"reason", "source_ip"},
		ErrorCode:      ErrAuthInvalidCredentials,
	},
	EvtAuthLoginBackoffTriggered: {
		Actor:          ActorTypeAnonymous,
		Outcome:        OutcomeDenied,
		Severity:       SeverityWarn,
		Message:        "Backoff started for {user_id}: {delay_seconds}s",
		RequiredFields: []string{"user_id", "delay_seconds", "source_ip"},
		ErrorCode:      ErrAuthRateLimited,
	},
	EvtAuthTokenRejected: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeDenied,
		Severity:       SeverityInfo,
		Message:        "Token rejected ({reason}) jti={jti}",
		RequiredFields: []string{"reason", "jti", "request_id"},
		ErrorCode:      ErrAuthInvalidToken,
	},
	EvtAuthRefreshRotated: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityInfo,
		Message:        "Refresh rotated for {user_id}",
		RequiredFields: []string{"user_id", "old_jti", "new_jti"},
		ErrorCode:      "",
	},
	EvtAuthRefreshReplayDetected: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeDenied,
		Severity:       SeverityCritical,
		Message:        "Refresh replay detected for {user_id}; all sessions revoked",
		RequiredFields: []string{"user_id", "replayed_jti", "source_ip"},
		ErrorCode:      ErrAuthInvalidToken,
	},
	EvtAuthLogout: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityInfo,
		Message:        "Logout for {user_id}",
		RequiredFields: []string{"user_id", "session_jti"},
		ErrorCode:      "",
	},
	EvtAuthLogoutAll: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityInfo,
		Message:        "All sessions revoked for {user_id}",
		RequiredFields: []string{"user_id"},
		ErrorCode:      "",
	},
	EvtAuthSessionRevoked: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityInfo,
		Message:        "Session {revoked_jti} revoked by {user_id}",
		RequiredFields: []string{"user_id", "revoked_jti"},
		ErrorCode:      "",
	},
	EvtAuthPasswordResetCompleted: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityWarn,
		Message:        "Password reset completed for {user_id}",
		RequiredFields: []string{"user_id", "source_ip"},
		ErrorCode:      "",
	},
	EvtAdminActionPerformed: {
		Actor:          ActorTypeSystemAdmin,
		Outcome:        OutcomeSuccess,
		Severity:       SeverityWarn,
		Message:        "Admin {admin_id} performed {action} on {target_user_id}",
		RequiredFields: []string{"action", "admin_id", "target_user_id", "request_id"},
		ErrorCode:      "",
	},
	EvtAdminActionDenied: {
		Actor:          ActorTypeUser,
		Outcome:        OutcomeDenied,
		Severity:       SeverityWarn,
		Message:        "Forbidden admin access attempt by {user_id} on {path}",
		RequiredFields: []string{"user_id", "path", "request_id"},
		ErrorCode:      ErrAuthForbidden,
	},
}
